# Generated by Django 5.1.7 on 2025-04-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionGL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('signature', models.TextField()),
                ('description', models.TextField()),
                ('feature', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FunctionVK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('signature', models.TextField()),
                ('description', models.TextField()),
                ('feature', models.TextField()),
            ],
        ),
    ]
